<?php
/* 
 * Generated by CRUDigniter v3.4 
 * www.crudigniter.com
 */
 
class Asignaturas_estudiante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asignaturas_estudiante by id
     */
    function get_asignaturas_estudiante($id)
    {
        return $this->db->get_where('asignaturas_estudiante',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all asignaturas_estudiante
     */
    function get_all_asignaturas_estudiante()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('asignaturas_estudiante')->result_array();
    }
        
    /*
     * function to add new asignaturas_estudiante
     */
    function add_asignaturas_estudiante($params)
    {
        $this->db->insert('asignaturas_estudiante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asignaturas_estudiante
     */
    function update_asignaturas_estudiante($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('asignaturas_estudiante',$params);
    }
    
    /*
     * function to delete asignaturas_estudiante
     */
    function delete_asignaturas_estudiante($id)
    {
        return $this->db->delete('asignaturas_estudiante',array('id'=>$id));
    }
}
