<?php
/* 
 * Generated by CRUDigniter v3.4 
 * www.crudigniter.com
 */
 
class Lugare_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lugare by id
     */
    function get_lugare($id)
    {
        return $this->db->get_where('lugares',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all lugares
     */
    function get_all_lugares()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('lugares')->result_array();
    }
        
    /*
     * function to add new lugare
     */
    function add_lugare($params)
    {
        $this->db->insert('lugares',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lugare
     */
    function update_lugare($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('lugares',$params);
    }
    
    /*
     * function to delete lugare
     */
    function delete_lugare($id)
    {
        return $this->db->delete('lugares',array('id'=>$id));
    }
}
